import { StyleSheet, Platform, StatusBar as RNStatusBar } from 'react-native';
import { SPACING, SHADOW } from '../theme';

export const getStyles = (theme, isDarkMode) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
  },
  menuButton: {
    marginRight: 16,
  },
  headerTitle: {
    fontSize: 20,
    color: '#FFF',
    fontFamily: 'Inter_600SemiBold',
    flex: 1,
  },
  themeToggle: {
    padding: 8,
    marginLeft: 10,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    flex: 1,
  },
  list: {
    paddingBottom: 40,
  },
  row: {
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  tile: {
    backgroundColor: theme.colors.surface,
    width: '31.5%',
    aspectRatio: 1,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: theme.colors.border,
  },
  tileIconContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  tileTitle: {
    fontSize: 12.5,
    color: theme.colors.text,
    fontFamily: 'Inter_600SemiBold',
    textAlign: 'center',
    paddingHorizontal: 2,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    padding: 28,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modalIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.colors.primary + '10', // 10% opacity
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: 'Inter_700Bold',
    color: theme.colors.text,
    marginBottom: 12,
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: 15,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.textLight,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
  },
  modalButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 14,
    width: '100%',
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'Inter_600SemiBold',
  },
  
  // Analytics Dashboard Styles
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    color: theme.colors.text,
    marginBottom: 10,
    marginTop: 4,
  },
  kpiIconContainer: {
    width: 26,
    height: 26,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 10,
  },
  heroLabel: {
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.textLight,
  },
  heroValue: {
    fontSize: 20,
    fontFamily: 'Inter_700Bold',
    color: theme.colors.text,
    marginTop: 1,
  },
  statScroll: {
    marginBottom: 12,
  },
  statScrollContent: {
    paddingRight: 4,
  },
  statChip: {
    minWidth: 78,
    backgroundColor: theme.colors.surface,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginRight: 8,
    alignItems: 'center',
  },
  statChipValue: {
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    color: theme.colors.text,
    marginBottom: 2,
  },
  statChipLabel: {
    fontSize: 11.5,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.textLight,
    textAlign: 'center',
  },
  yearCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 8,
  },
  yearText: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.text,
    lineHeight: 18,
    marginLeft: 8,
  },

  // Global Search Modal
  searchModalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 16,
  },
  searchModalBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 46,
  },
  searchModalInput: {
    flex: 1,
    fontSize: 15,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.text,
    marginLeft: 8,
    height: '100%',
  },
  searchCancelBtn: {
    alignSelf: 'flex-end',
    paddingVertical: 10,
  },
  searchCancelText: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    color: theme.colors.primary,
  },
  searchResultsScroll: {
    flex: 1,
  },
  searchHint: {
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.textLight,
    textAlign: 'center',
    marginTop: 28,
    paddingHorizontal: 12,
    lineHeight: 19,
  },
  searchSection: {
    marginTop: 12,
  },
  searchSectionLabel: {
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    color: theme.colors.textLight,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  searchResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  searchResultIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  searchResultTitle: {
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    color: theme.colors.text,
  },
  searchResultSubtitle: {
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.textLight,
    marginTop: 1,
  },
  searchEmptyState: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  searchEmptyText: {
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    color: theme.colors.textLight,
    marginTop: 8,
  },
  searchSeeAllBtn: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  searchSeeAllText: {
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    color: theme.colors.primary,
  },
});
